FROM php:8.1-apache

RUN apt update && apt install -y zlib1g-dev g++ libicu-dev zip libzip-dev zip libpq-dev
RUN docker-php-ext-install intl opcache pdo_mysql 
RUN pecl install apcu 
RUN docker-php-ext-enable apcu 
RUN docker-php-ext-configure zip
RUN docker-php-ext-install zip
RUN apt-get install -y git 
RUN a2enmod rewrite

# xdebugのinstall
RUN pecl install xdebug \ 
 && docker-php-ext-enable xdebug


WORKDIR /var/www/html

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
